/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package amoba;

import javax.swing.JButton;

/**
 *
 * @author katona.janos
 */
public class amobaGUI extends javax.swing.JFrame {
    /**
     * Creates new form amobaGUI
     */
    static JButton gomb = new JButton();
    public amobaGUI() {
        
        initComponents();
        pinNumsOrderer();
        amobaPalya(amobaMeretJList.getSelectedIndex());
    }
    private void pinNumsOrderer() {
        for (int i = 1; i < 10; i++) {
            
            pinNumsJPanel.add(gomb);
            gomb.setText(String.valueOf(i));
            
            System.out.println("jo");
        }

        
          pinNumsJPanel.revalidate();
          pinNumsJPanel.repaint();
    }
           private void amobaPalya(int selectedIndex) {
               System.out.println(selectedIndex);
               for (int i = 0; i < (selectedIndex+3*selectedIndex+3); i++) {
                   
               }
           }
           
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        pinNumsJPanel = new javax.swing.JPanel();
        pinSpaceJPanel = new javax.swing.JPanel();
        keverJCheckBox = new javax.swing.JCheckBox();
        kodJLabel = new javax.swing.JLabel();
        passJTextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        amobaJPanel = new javax.swing.JPanel();
        jatekBeallitasJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        amobaMeretJList = new javax.swing.JList<>();
        xJRadioButton = new javax.swing.JRadioButton();
        oJRadioButton = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pinNumsJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Pin kód"));
        pinNumsJPanel.setToolTipText("");
        pinNumsJPanel.setLayout(new java.awt.GridLayout());

        pinSpaceJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Beállítás"));

        keverJCheckBox.setText("kever");
        keverJCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keverJCheckBoxActionPerformed(evt);
            }
        });

        kodJLabel.setText("kód:");

        javax.swing.GroupLayout pinSpaceJPanelLayout = new javax.swing.GroupLayout(pinSpaceJPanel);
        pinSpaceJPanel.setLayout(pinSpaceJPanelLayout);
        pinSpaceJPanelLayout.setHorizontalGroup(
            pinSpaceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinSpaceJPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(pinSpaceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kodJLabel)
                    .addComponent(keverJCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pinSpaceJPanelLayout.setVerticalGroup(
            pinSpaceJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pinSpaceJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(keverJCheckBox)
                .addGap(18, 18, 18)
                .addComponent(kodJLabel)
                .addGap(18, 18, 18)
                .addComponent(passJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pinNumsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(pinSpaceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pinSpaceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pinNumsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bejelentkezés", jPanel1);

        amobaJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Amőba"));

        javax.swing.GroupLayout amobaJPanelLayout = new javax.swing.GroupLayout(amobaJPanel);
        amobaJPanel.setLayout(amobaJPanelLayout);
        amobaJPanelLayout.setHorizontalGroup(
            amobaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        amobaJPanelLayout.setVerticalGroup(
            amobaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 161, Short.MAX_VALUE)
        );

        jatekBeallitasJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Beállítás"));

        amobaMeretJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "3x3", "4x4", "5x5", "6x6", "7x7" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(amobaMeretJList);

        buttonGroup1.add(xJRadioButton);
        xJRadioButton.setText("\"X\" kezd");

        buttonGroup1.add(oJRadioButton);
        oJRadioButton.setText("\"O\" kezd");

        javax.swing.GroupLayout jatekBeallitasJPanelLayout = new javax.swing.GroupLayout(jatekBeallitasJPanel);
        jatekBeallitasJPanel.setLayout(jatekBeallitasJPanelLayout);
        jatekBeallitasJPanelLayout.setHorizontalGroup(
            jatekBeallitasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatekBeallitasJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jatekBeallitasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xJRadioButton)
                    .addComponent(oJRadioButton))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jatekBeallitasJPanelLayout.setVerticalGroup(
            jatekBeallitasJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jatekBeallitasJPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(xJRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(oJRadioButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(amobaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jatekBeallitasJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jatekBeallitasJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(amobaJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Játék", jPanel2);

        jMenu1.setText("Program");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Játék elrendezése");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keverJCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keverJCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keverJCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amobaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amobaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amobaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amobaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amobaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel amobaJPanel;
    private javax.swing.JList<String> amobaMeretJList;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jatekBeallitasJPanel;
    private javax.swing.JCheckBox keverJCheckBox;
    private javax.swing.JLabel kodJLabel;
    private javax.swing.JRadioButton oJRadioButton;
    private javax.swing.JTextField passJTextField;
    private javax.swing.JPanel pinNumsJPanel;
    private javax.swing.JPanel pinSpaceJPanel;
    private javax.swing.JRadioButton xJRadioButton;
    // End of variables declaration//GEN-END:variables




}
